apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: 1ds23cs403/your-docker-image:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred  # This tells Kubernetes to use the 'regcred' secret for pulling the image
